/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ElderIndexRouteImport } from './routes/elder/index'
import { Route as ElderHelpRouteImport } from './routes/elder/help'
import { Route as ElderPeopleRouteImport } from './routes/elder/people'
import { Route as ElderPlayRouteImport } from './routes/elder/play'
import { Route as ElderRoutineRouteImport } from './routes/elder/routine'
import { Route as ElderModesDomainRouteImport } from './routes/elder/modes.$domain'
import { Route as ElderGameDomainModeRouteImport } from './routes/elder/game.$domain.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderIndexRoute = ElderIndexRouteImport.update({
  id: '/elder/',
  path: '/elder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderHelpRoute = ElderHelpRouteImport.update({
  id: '/elder/help',
  path: '/elder/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderPeopleRoute = ElderPeopleRouteImport.update({
  id: '/elder/people',
  path: '/elder/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderPlayRoute = ElderPlayRouteImport.update({
  id: '/elder/play',
  path: '/elder/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderRoutineRoute = ElderRoutineRouteImport.update({
  id: '/elder/routine',
  path: '/elder/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderModesDomainRoute = ElderModesDomainRouteImport.update({
  id: '/elder/modes/$domain',
  path: '/elder/modes/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderGameDomainModeRoute = ElderGameDomainModeRouteImport.update({
  id: '/elder/game/$domain/$mode',
  path: '/elder/game/$domain/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRoute
  '/government': typeof GovernmentRoute
  '/api/tts': typeof ApiTtsRoute
  '/elder/help': typeof ElderHelpRoute
  '/elder/people': typeof ElderPeopleRoute
  '/elder/play': typeof ElderPlayRoute
  '/elder/routine': typeof ElderRoutineRoute
  '/elder/': typeof ElderIndexRoute
  '/elder/modes/$domain': typeof ElderModesDomainRoute
  '/elder/game/$domain/$mode': typeof ElderGameDomainModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRoute
  '/government': typeof GovernmentRoute
  '/api/tts': typeof ApiTtsRoute
  '/elder/help': typeof ElderHelpRoute
  '/elder/people': typeof ElderPeopleRoute
  '/elder/play': typeof ElderPlayRoute
  '/elder/routine': typeof ElderRoutineRoute
  '/elder': typeof ElderIndexRoute
  '/elder/modes/$domain': typeof ElderModesDomainRoute
  '/elder/game/$domain/$mode': typeof ElderGameDomainModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/doctor': typeof DoctorRoute
  '/government': typeof GovernmentRoute
  '/api/tts': typeof ApiTtsRoute
  '/elder/help': typeof ElderHelpRoute
  '/elder/people': typeof ElderPeopleRoute
  '/elder/play': typeof ElderPlayRoute
  '/elder/routine': typeof ElderRoutineRoute
  '/elder/': typeof ElderIndexRoute
  '/elder/modes/$domain': typeof ElderModesDomainRoute
  '/elder/game/$domain/$mode': typeof ElderGameDomainModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caregiver'
    | '/doctor'
    | '/government'
    | '/api/tts'
    | '/elder/help'
    | '/elder/people'
    | '/elder/play'
    | '/elder/routine'
    | '/elder/'
    | '/elder/modes/$domain'
    | '/elder/game/$domain/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caregiver'
    | '/doctor'
    | '/government'
    | '/api/tts'
    | '/elder/help'
    | '/elder/people'
    | '/elder/play'
    | '/elder/routine'
    | '/elder'
    | '/elder/modes/$domain'
    | '/elder/game/$domain/$mode'
  id:
    | '__root__'
    | '/'
    | '/caregiver'
    | '/doctor'
    | '/government'
    | '/api/tts'
    | '/elder/help'
    | '/elder/people'
    | '/elder/play'
    | '/elder/routine'
    | '/elder/'
    | '/elder/modes/$domain'
    | '/elder/game/$domain/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaregiverRoute: typeof CaregiverRoute
  DoctorRoute: typeof DoctorRoute
  GovernmentRoute: typeof GovernmentRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ElderHelpRoute: typeof ElderHelpRoute
  ElderPeopleRoute: typeof ElderPeopleRoute
  ElderPlayRoute: typeof ElderPlayRoute
  ElderRoutineRoute: typeof ElderRoutineRoute
  ElderIndexRoute: typeof ElderIndexRoute
  ElderModesDomainRoute: typeof ElderModesDomainRoute
  ElderGameDomainModeRoute: typeof ElderGameDomainModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/': {
      id: '/elder/'
      path: '/elder'
      fullPath: '/elder/'
      preLoaderRoute: typeof ElderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/help': {
      id: '/elder/help'
      path: '/elder/help'
      fullPath: '/elder/help'
      preLoaderRoute: typeof ElderHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/people': {
      id: '/elder/people'
      path: '/elder/people'
      fullPath: '/elder/people'
      preLoaderRoute: typeof ElderPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/play': {
      id: '/elder/play'
      path: '/elder/play'
      fullPath: '/elder/play'
      preLoaderRoute: typeof ElderPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/routine': {
      id: '/elder/routine'
      path: '/elder/routine'
      fullPath: '/elder/routine'
      preLoaderRoute: typeof ElderRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/modes/$domain': {
      id: '/elder/modes/$domain'
      path: '/elder/modes/$domain'
      fullPath: '/elder/modes/$domain'
      preLoaderRoute: typeof ElderModesDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder/game/$domain/$mode': {
      id: '/elder/game/$domain/$mode'
      path: '/elder/game/$domain/$mode'
      fullPath: '/elder/game/$domain/$mode'
      preLoaderRoute: typeof ElderGameDomainModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaregiverRoute: CaregiverRoute,
  DoctorRoute: DoctorRoute,
  GovernmentRoute: GovernmentRoute,
  ApiTtsRoute: ApiTtsRoute,
  ElderHelpRoute: ElderHelpRoute,
  ElderPeopleRoute: ElderPeopleRoute,
  ElderPlayRoute: ElderPlayRoute,
  ElderRoutineRoute: ElderRoutineRoute,
  ElderIndexRoute: ElderIndexRoute,
  ElderModesDomainRoute: ElderModesDomainRoute,
  ElderGameDomainModeRoute: ElderGameDomainModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
